#!/bin/sh
get_vol() {
    data="$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oE ...% | head -1)"
    echo ${data%?}
}

get_vol

pactl subscribe | grep --line-buffered "sink" | while read -r line; do
    if [ ! -z "$(pactl get-sink-mute @DEFAULT_SINK@ | grep no)" ]; then
        get_vol
    else
        echo 0
    fi
done

