#!/bin/sh
hyprctl activewindow -j | jq --raw-output .title
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | \
    stdbuf -o0 awk -F '>>|,' '/^activewindow>>/{print "%s\t", $1; system(sprintf("fold -sw 50 <<< \"%s\" | sed q", $3))}'